version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: dblogin
      POSTGRES_USER: link
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: